### ISSUE TITLE
CRL support

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#10]
This is a placeholder for CRL support via WebSockets implementation.
- [X] Fetch CRL asyncronously
- [x] Move CRL to Amazon Web Services / CDN
  - Done 5/29 via https://crl.qz.io --> https://d394qbcjy82lwe.cloudfront.net/

**Comment by robertcasto** [comment]
Steven is in all day today so I will have him take a look.

**Comment by sjennison** [comment]
CRL support should be functional now on latest 1.9

you will need to change the URL in CRL.java to point to the correct location. Should be an easy change.

**Comment by tresf** [comment]
Terrific.   I made some more comments in the commit area.  I'll switch over the URL now.

**Comment by tresf** [comment]
Since the asyncronous fetching was introduced, this CRL fetch seems to be failing in the log file.  Can we get a sanity check that this is still working?

Also, @robertcasto @bberenz I could still use some assistance setting up CRL up with a CDN such as Amazon.  Is this something your team could help with?  I assume I'll have to purchase something, change some DNS entries, etc and if I could get some help from someone familiar with this process that would be a big time saver.

**Comment by robertcasto** [comment]
Steven is looking into this.

On Tue, May 5, 2015 at 11:43 AM, Tres Finocchiaro notifications@github.com
wrote:

> Since the asyncronous fetching was introduced, this CRL fetch seems to be
> failing in the log file. Can we get a sanity check that this is still
> working?
> 
> Also, @robertcasto https://github.com/robertcasto @bberenz
> https://github.com/bberenz I could still use some assistance setting up
> CRL up with a CDN such as Amazon. Is this something your team could help
> with? I assume I'll have to purchase something, change some DNS entries,
> etc and if I could get some help from someone familiar with this process
> that would be a bit time saver.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/10#issuecomment-99120417.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
Thanks it looks like it was a false-positive in the code which is great.

Now that is fixed... How about the CDN stuff?

**Comment by tresf** [comment]
Ok... I setup the CDN side here:
https://s3.amazonaws.com/qztray/crl

Now I just need help pointing the http://crl.qzindustries.com to the amazon location.

**Comment by robertcasto** [comment]
If that is just a redirect, then it is fairly easy to do through DNS with
that subdomain. Is qzindustries.com registered with godaddy? If so, I can
walk you through the process.

On Tue, May 5, 2015 at 1:38 PM, Tres Finocchiaro notifications@github.com
wrote:

> Ok... I setup the CDN side here:
> https://s3.amazonaws.com/qztray/crl
> 
> Now I just need help pointing the http://crl.qzindustries.com to the
> amazon location.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/10#issuecomment-99154647.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
I think I got it.  Looks like Godaddy does the heavy lifting in terms of adding the DNS address, etc.  

http://crl.qzindustries.com

**Comment by robertcasto** [comment]
Yup. Looks like it is working. :)

On Tue, May 5, 2015 at 4:08 PM, Tres Finocchiaro notifications@github.com
wrote:

> I think I got it. Looks like Godaddy does the heavy lifting in terms of
> adding the DNS address, etc.
> 
> http://crl.qzindustries.com
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/10#issuecomment-99206023.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
**Edit:**  The new CRL is live at https://crl.qz.io, via https://github.com/qzind/qz-print/commit/94e7f401596894bce5815e84be33c7e1b7886e3b

---

A slight update on this, after some trial and error with the AWS command line interface, I've managed to get HTTPS working with the Amazon bucket and the AlphaSSL certificate via [Bryce Fisher-Fleig's tutorial](https://bryce.fisher-fleig.org/blog/setting-up-ssl-on-aws-cloudfront-and-s3/).

This gets a working SSL at https://d394qbcjy82lwe.cloudfront.net but we need to configure DNS and allow TTL expiration/propagation to get the future https://crl.qz.io working.

**Install aws CLI** (For Mac; Linux instructions [here](http://docs.aws.amazon.com/cli/latest/userguide/installing.html#d0e669))

``` bash
brew up
brew install aws-cfn-tools awscli
```

**Upload certificate and private key**

``` bash
aws configure
#enter AWS Access Key ID 
#enter AWS Secret Access Key
#Default region name: us-east-1
#Default output format: json

aws iam upload-server-certificate
--server-certificate-name crl.qz.io \
--certificate-body file://qz.io-combined.crt \
--private-key file://qz.io-private.key \
--path /cloudfront/
# Note: --certificate-chain option found in many examples WAS NOT NEEDED for the AlphaSSL certificate
```
