### ISSUE TITLE
clearException() method not working as expected

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#103]
Quoting the original bug report which came in via email:

> In the `qzDonePrinting` method if there is an exception it alerts the exception and then calls `clearException()`.  The first time there is a printing exception the alert reports correctly but it appears that the exception is NOT cleared.  If you successfully print again the print works fine with no errors but the `getException()` method still returns a valid object but `getLocalizedMessage()` returns null.

The offending code appears to be here:

https://github.com/qzind/qz-print/blob/1.9/js/qz-websocket.js#L189:L197

**Comment by tresf** [comment]
@bberenz I spent a couple hours on this and I'm in a tailspin trying to figure out why `getException` never gets cleared.

Can you take a look?  This is a core function that seems to have been broken since the release of QZ Tray.

**Comment by akberenz** [comment]
I think your confusion came from the weird way we are handling exceptions in 1.9, because we always send a result when the exception value changes, even on null, and re-purpose it to be a property on a js object.
https://github.com/qzind/qz-print/blob/1.9/src/qz/ws/PrintSocket.java#L352

**Comment by tresf** [comment]
@bberenz Thanks that was my first instinct, but now when you try to print an XPS document and "Cancel" at the "Save As" screen, it doesn't fire an exception because `getLocalizedMessage` is `null`.  Shall we also add in an:

``` java
// pseudocode
if (qz.getException().getLocalizedMessage() == null) {
   eMsg = qz.getException().getClass().getName(); // or perhaps "Unknown Error"
}
```

**Comment by akberenz** [comment]
Yes, we should. I've added it under 9a9fa61190db52d4938b0ab8651faa63ef24436c.

**Comment by tresf** [comment]
:+1: 

![image](https://cloud.githubusercontent.com/assets/6345473/11186999/7a303ed8-8c52-11e5-9583-e0dc38cddd2c.png)
