### ISSUE TITLE
Windows 10 - Fix QZ Tray launcher

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#106]
@klabarge Can you investigate as to why the launcher won't show up when searching for "QZ" in the Windows 10 start menu?

**Comment by klabarge** [comment]
After updating to QZ Tray 1.9.4-patch 1, QZ Tray shows up when searching for "qz."

Should I look for a solution in older versions?

![image](https://cloud.githubusercontent.com/assets/12505463/11249918/bd6101b4-8df7-11e5-8996-9e4e1370fd92.png)

**Comment by tresf** [comment]
No, that's perfect.  Closed via https://github.com/qzind/qz-print/commit/4c408122fbe548031ee5c163bfa15565184c650a, which adds a dedicated `.exe` launcher for Windows.  Thanks!!
