### ISSUE TITLE
Page Refresh/GatewayDialog

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#11]
The Gateway dialog doesn't behave properly with page refreshes... It displays for the first WebSocket connection and the refreshed page doesn't receive the "Allow".

Steps to reproduce:
1. Run QZ Tray
2. Load `sample_ws.html` in a Web Browser.
3. Click the tray to display the GatewayDialog
4. Leave the GatewayDialog open and refresh the page on the browser
5. Switch to the GatewayDialog, click Allow.
6. Switch back to the web page, it is still yellow.

**Comment by akberenz** [comment]
Should be fixed via 5735b32ba5ceeb44640e94f83e0a81473985110d, the dialogs will now get queued up and displayed to the user.

**Comment by tresf** [comment]
@bberenz Terrific, thank you. @robertcasto this even works with the "Always Allow" because the dialog itself checks the certificate which checks the whitelist, thus essentially clicking "Yes" for every dialog that appears (so one "Yes" suppresses them all if the "Always allow" is checked.  This works terrifically.

**Comment by robertcasto** [comment]
This is good to hear. Hopefully the other changes will go just as well.

On Wed, May 6, 2015 at 3:57 PM, Tres Finocchiaro notifications@github.com
wrote:

> @bberenz https://github.com/bberenz Terrific, thank you. @robertcasto
> https://github.com/robertcasto this even works with the "Always Allow"
> because the dialog itself checks the certificate which checks the
> whitelist, thus essentially clicking "Yes" for every dialog that appears.
> This works terrifically.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/11#issuecomment-99586981.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
FYI, added new `ConfirmDialog` vi https://github.com/qzind/qz-print/commit/7598bddd61f924fa64c9d66048ee2524f65b64e3 for UI consistency and also to allow `setAlwaysOnTop(true);` similar to `GatewayDialog` as this too was getting hid behind other windows.

![image](https://cloud.githubusercontent.com/assets/6345473/7626350/b15dfacc-f9d5-11e4-8db1-66d56b9bcf15.png)
