### ISSUE TITLE
Option to reduce console.log verbosity

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#111]
Currently the web console log is very busy with websocket messages.  The option to reduce the verbosity would be nice for developers that may need to parse the log for non-qz related events.

**Comment by nhouse** [comment]
Perhaps you could add a flag to `qzConfig` like `showDebugOutput` set to `true` by default. So then I could do:

```
qzConfig.showDebugOutput = false;
deployQZ();
```

Then you could change you `console.log()` statements from:

```
console.log(WebSocket);
```

To:

```
if (qzConfig.showDebugOutput) { console.log(WebSocket); }
```

**Comment by tresf** [comment]
Stared via https://github.com/qzind/qz-print/pull/119.  @bberenz, etc, feedback welcome.

**Comment by akberenz** [comment]
Already being taken care of as `_qz.DEBUG` in the 2.0 branch, to address this very issue.
I can port the logging level code, if you'd rather the fine level control.

**Comment by tresf** [comment]
@bberenz thanks for the quick response.

I'll keep consistent with 2.0 then.  Simplified via https://github.com/qzind/qz-print/commit/4db4d684365ae2dd4d21da5df2b4b8f6c2465685.  Second set of eyes is greatly appreciated.
