### ISSUE TITLE
Support for CPCL (Zebra) print templates?

### ISSUE THREAD

**Issue by jamesmosier** [qzind/qz-print#112]
After much research, I was unable to find any information on whether or not qz-print has any support for the Zebra print template language CPCL. I know ZPL is its cousin, but not the same. I looked at the various methods that hang off of the `qz` object in JavaScript, but did not see any related to `appendCPCL` or anything of the sorts.

I tried to do a simple CPCL print test by doing this below, with no luck.

```
qz.append('! 0 200 200 210 1');
qz.append('CENTER');
qz.append('TEXT 4 3 0 0 Centered Company Name');
qz.append('LEFT');
qz.append('TEXT 4 3 0 0 Text on left');
qz.append('FORM');
qz.append('PRINT');

qz.print();
```

With that being said, is there any support for CPCL currently available?

**Comment by lite1979** [comment]
James:

We do support text and barcode printing in CPCL, but we have no hardware to
test on. Image printing in CPCL is not yet supported by QZ-Print.

What model printer do you have? Is it set up as a raw/generic queue, or are
you using the Zebra driver?

Here is a 'Hello World' from the CPCL programming manual:

qz.append('! 0 200 200 210 1');
qz.append('TEXT 4 0 30 40 Hello World');
qz.append('FORM');
qz.append('PRINT');
qz.print();

Regarding the example code you provided us, did you get any error messages
from the print job? Are you using QZ-Tray? If so, go to 'Advanced' and make
sure "block anonymouse requests" is not checked, or the print job will fail
silently.

Regards,

Lite Finocchiaro

**Comment by jamesmosier** [comment]
Hi Lite,

Thanks for the quick response. I am using QZ-Tray and I have been able to successfully print the example ZPL to my printer (of course it doesn't look correct, but it prints!) but not my own CPCL code. I replaced my code with the example above and it still failed to print. It does prompt me to "allow" the connection (which it always does) which I allowed and also showed an alert stating "Successfully sent print data to zebra queue.". 
`zebra` is the name of the printer I setup using just the raw/generic drivers (not any special Zebra drivers). Also the "block anonymous requests" is not checked. 

The model of printer I am using is a Zebra QLn420. 

I have attached a screenshot of my console, showing what messages come up after I allow connections and the alert saying it is queued shows up. I've inspected the various objects but nothing of importance seems to be in there, at least in reference to any errors. 

Is there any other info I can look at during debugging to possibly track this down? 

Thanks again,
James

![image](https://cloud.githubusercontent.com/assets/2854919/11346732/fcc8ff3a-91eb-11e5-9b06-e6e87cd1339b.png)

**Comment by jamesmosier** [comment]
I was able to get this to print! I just had to add line breaks to each line. So (fingers crossed) in theory I should be able to get my own template to print using the same methodology. Thanks for your help!

```
qz.append('! 0 200 200 210 1\n');
qz.append('TEXT 4 0 30 40 Hello World\n');
qz.append('FORM\n');
qz.append('PRINT\n');
qz.print();
```

**Comment by lite1979** [comment]
Wonderful! Thanks for the update, James.

**Comment by jamesmosier** [comment]
No problem! Still having trouble printing my own template (they just all get stuck in the print queue), but hopefully I'll be able to make a breakthrough soon. Thanks again!
