### ISSUE TITLE
Open file location Linux QZ Tray

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#116]
Tested on Ubuntu 14.04 64-bit

After compiling and installing the latest version of QZ Tray (1.9.5), **Right click > Advanced > Open file location** does not work.

![image](https://cloud.githubusercontent.com/assets/12505463/11463562/a88c298c-96f1-11e5-9062-09a245a1917a.png)

**Comment by tresf** [comment]
Tested on:
- :white_check_mark: **PASS** `Ubuntu 12.04 x64`, `OpenJDK 1.7.0_79`
- :white_check_mark: **PASS** `Ubuntu 14.04 x64`, `OpenJDK 1.7.0_91`
- :no_entry_sign: **FAIL** `Ubuntu 14.04 x64`, `Oracle Java 1.7.0_72`

![image](https://cloud.githubusercontent.com/assets/6345473/11473353/e34509d8-973f-11e5-9c64-a6b859968c29.png)

I've put `xdg-open` fallback in the code via d6cc780 for the edge-cases where it won't open the file location.  @klabarge please re-test.
