### ISSUE TITLE
2.0.0-alpha1 installer shortcut is wrong

### ISSUE THREAD

**Issue by robert-gazsi** [qzind/qz-print#128]
The installer is running without issues and the log shows no errors (windows 10).
However, the desktop app shortcut installed in start menu does not work, maybe It was left over from a previously installed version.
Also, the app was not started, and not present in systray.
I started it successfully if I manually launched the qz-tray.jar file.

**Comment by tresf** [comment]
Thanks.  Closed via 858ba18.

Patched installer located here:
https://github.com/tresf/qz-print/releases/tag/2.0.0-alpha1
