### ISSUE TITLE
2.0.0-alpha1 pdf print scale issue

### ISSUE THREAD

**Issue by robert-gazsi** [qzind/qz-print#129]
Pdf content is printed at top left corner at about 5% of the whole page size.
See attached sample.
[test.pdf](https://github.com/qzind/qz-print/files/75456/test.pdf)

**Comment by tresf** [comment]
@robert-gazsi is this with a physical printer or the Microsoft XPS/PDF document writer?  We're experiencing issues with print simulations using the Windows 10 XPS document writer, but we aren't having the same problems while doing print simulations 3rd party PDF writers.

Either way we'll fully investigate and report back. Thanks for the write-up.

**Comment by robert-gazsi** [comment]
Yes, I have printed it physically on a HP LaserJet 1020, with same result.
Thanks for your prompt response.
Pe 31.12.2015 21:13, "Tres Finocchiaro" notifications@github.com a scris:

**Comment by akberenz** [comment]
What is the DPI setting of the printers you are using, and the DPI value you are passing to qz-tray?

**Comment by robert-gazsi** [comment]
My bad, I realized I have to change the "Density" property in the 
Options section from 72 to 600 to match my printer dpi.
It would be helpful, in my opinion, to rename this property to Density 
(DPI).
Thanks!

**Comment by tresf** [comment]
> It would be helpful, in my opinion, to rename this property to Density (DPI).

Agreed... @bberenz I started a commit which adds `DPI`, `mm/in` etc to `pxlDensity` label, however it started getting more complicated than I had anticipated, as the 72dpi would need to be translated on click, which started getting messy.  Which leads me to my next question... 

> What is the DPI setting of the printers you are using, and the DPI value you are passing to qz-tray?

@bberenz The [Java source](https://github.com/qzind/qz-print/blob/2.0/src/qz/printer/PrintOptions.java#L220) and [jsDocs](https://github.com/qzind/qz-print/blob/2.0/js/qz-tray.js#L620) state this density depends on `options.units` but is that true?  It appears to [internally use inches](https://github.com/qzind/qz-print/blob/2.0/src/qz/printer/action/PrintPixel.java#L54) and convert (i.e. PDF) [at time of printing](https://github.com/qzind/qz-print/blob/2.0/src/qz/printer/action/PrintPDF.java#L69) to the appropriate unit, no?  Regardless of standard/metric page sizes, I seem to be finding that DPI is the accepted standard in regards to print quality, is this correct?

Secondly, at least for purposes of the demo, we should make scaling on PDFs done by default.

**Edit: 2016-02-03** Autoscale is on by default now and scaling bugs are fixed via c7acaac.
