### ISSUE TITLE
Windows Installer Ignores /D Parameter

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#132]
NSIS offers a command line parameter `/D=C:\Foo` and our installer ignores it.

This means our documentation is broken as the [Unattended Deployment](https://github.com/qzind/qz-print/wiki/Deployment) steps claim the directory can be overridden via `/D=C:\Foo`, but this is not honored in our version of the installer.

According to [this article](http://stackoverflow.com/questions/14272992/how-can-i-know-if-d-parameter-was-passed-into-nsis-based-installer), this may be due to the fact that we specify it here [`windows-packager.nsi.in#L20`](https://github.com/qzind/qz-print/blob/1.9/ant/windows/windows-packager.nsi.in#L20).

We need to find a way to accept the command line path, if supplied so that non-standard installation locations are honored via command line.

**Comment by Vzor-** [comment]
I'm on this one.

**Comment by tresf** [comment]
:+1:
