### ISSUE TITLE
Persistent USB Dialogs

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#133]
The USB alert dialogs have a lot of info on them, but the default window timeout is too quick to grab the necessary information for device iteration.

I think making these alert dialogs persistent (user would have to close them manually) would make them much easier to use for grabbing device information.

![image](https://cloud.githubusercontent.com/assets/6345473/12190293/e2dac802-b594-11e5-87ad-0c72c3af936f.png)

**Comment by akberenz** [comment]
Closed with 05446a79ff24cea8ddbf6d486c578ec6a68a6165
