### ISSUE TITLE
setCertificatePromise bypass

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#139]
@bberenz thoughts appreciated here... 

Currently with the `2.0` branch, the recommended method for setting the certificate is as follows:

``` javascript
qz.security.setCertificatePromise(function(resolve) {
   resolve($.ajax("path/to/digitial-certificate.txt"));
});
```

However, this certificate step can be bypassed completely by commenting out this block, and there's no sign to the user that the certificate wasn't provided.

``` javascript
/*qz.security.setCertificatePromise(function(resolve) {
   resolve($.ajax("foo/bar.txt"));
});*/
```

![image](https://cloud.githubusercontent.com/assets/6345473/12379264/b9ead382-bd24-11e5-80d5-2ae813e5e252.png)

From a security perspective, this is relatively minor, since the privileged commands will all fail due to an invalid certificate, however there's no sign that the cert is missing and the untrusted dialog doesn't show in this scenario, which is different than the behavior in 1.9.

Note, this can also be simulated by giving a bad URL, i.e.

``` javascript
qz.security.setCertificatePromise(function(resolve) {
   resolve($.ajax("invalid/path.txt"));
});
```

**Comment by akberenz** [comment]
Fixed via eafcd9d4f8b2decc7b3e2c5966e3a42e1c969d95
