### ISSUE TITLE
Notification when QZ Tray is not running

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#14]
@bberenz @robertcasto can we put in logic to display an alert when QZ Tray is not running?

**Comment by tresf** [comment]
Clarification... this would be on page load.

**Comment by robertcasto** [comment]
You mean when the Javascript cannot find the websocket? Yes, that can be
done.

On Wed, Mar 25, 2015 at 2:29 PM, Tres Finocchiaro notifications@github.com
wrote:

> Clarification... this would be on page load.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/14#issuecomment-86160875.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by robertcasto** [comment]
What kind of notification would you like? Popup dialog? Message dialog that
goes away after a little while?

On Wed, Mar 25, 2015 at 3:15 PM, Robert Casto casto.robert@gmail.com
wrote:

> You mean when the Javascript cannot find the websocket? Yes, that can be
> done.
> 
> On Wed, Mar 25, 2015 at 2:29 PM, Tres Finocchiaro <
> notifications@github.com> wrote:
> 
> > Clarification... this would be on page load.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/qzind/qz-print/issues/14#issuecomment-86160875.
> 
> ## 
> 
> Robert Casto
> _Owner | SellersToolbox_
> p: 1-513-847-4942
> c: 1-513-886-1550
> e: casto.robert@gmail.com
> www.sellerstoolbox.com
> Tools for Amazon Sellers

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by robertcasto** [comment]
Brett instead made it so you can supply a function that can do whatever
kind of alert you want. The change has already been checked in.

On Wed, Mar 25, 2015 at 3:16 PM, Robert Casto casto.robert@gmail.com
wrote:

> What kind of notification would you like? Popup dialog? Message dialog
> that goes away after a little while?
> 
> On Wed, Mar 25, 2015 at 3:15 PM, Robert Casto casto.robert@gmail.com
> wrote:
> 
> > You mean when the Javascript cannot find the websocket? Yes, that can be
> > done.
> > 
> > On Wed, Mar 25, 2015 at 2:29 PM, Tres Finocchiaro <
> > notifications@github.com> wrote:
> > 
> > > Clarification... this would be on page load.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/qzind/qz-print/issues/14#issuecomment-86160875.
> > 
> > ## 
> > 
> > Robert Casto
> > _Owner | SellersToolbox_
> > p: 1-513-847-4942
> > c: 1-513-886-1550
> > e: casto.robert@gmail.com
> > www.sellerstoolbox.com
> > Tools for Amazon Sellers
> 
> ## 
> 
> Robert Casto
> _Owner | SellersToolbox_
> p: 1-513-847-4942
> c: 1-513-886-1550
> e: casto.robert@gmail.com
> www.sellerstoolbox.com
> Tools for Amazon Sellers

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
Closed via https://github.com/qzind/qz-print/commit/4080322b2abe1432279f6235c2824f676648a393

:+1:
