### ISSUE TITLE
Base64 PDF Bug

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#141]
@bberenz since we're moving away from the `data:application/pdf;base64,JVBERi0xLjMKJcfsj6...==` syntax, I think now we're missing the `base64` functionality... 

``` javascript
var config = qz.configs.create("My Printer");
var data = [{
   type: 'pdf',
   format: 'base64',
   data: 'JVBERi0xLjMKJcfsj6...=='}];
qz.print(config, data);
```

Throws:

```
ERROR] 2016-01-18 09:29:17,348 @ qz.ws.PrintSocketClient:439
    Failed to print
java.lang.UnsupportedOperationException: Cannot parse (base64)JVBERi0xLjMKJcfsj6IKNSAwIG9iago8PC9MZW5nd...
```

My instinct is we'll need to add something like this to [`PrintPDF.java`](https://github.com/qzind/qz-print/blob/2.0/src/qz/printer/action/PrintPDF.java#L43):

``` java
pdfs.add(PDDocument.load(Base64.decode(data.getString("data"))));
```

**Comment by akberenz** [comment]
Fixed via 9e3942a15f55cb7a2ac85f061798c7a23b1a8cd0
