### ISSUE TITLE
Open Log Location Broken on Mac

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#148]
`2.0` branch.
Possibly related: #35, specifically [here](https://github.com/qzind/qz-print/commit/4c1a2685618940b98d055febf622db30b6e81da1#diff-a953e83b62c6bf3017ac9df374ffb42dR249).

**Comment by tresf** [comment]
Closed via 101e147.

@klabarge can you please test on all three platforms?  `2.0` branch only, please. ;)

**Comment by klabarge** [comment]
"Open log location" worked on all three platforms.
- Windows 10 :white_check_mark: 
- Ubuntu 14.04 :white_check_mark: 
- OS X 10.11 :white_check_mark:
