### ISSUE TITLE
Pixel-Accurate (Low-Res) Printing

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#149]
A picture does plenty to explain this... 

![image](https://cloud.githubusercontent.com/assets/6345473/12591750/5d663984-c437-11e5-8e8a-2be4ea97b838.png)

How to yield high pixel accuracy in a situation like this?  `2.0` branch.

The picture is tiny.  Below is actual size.

![image](https://cloud.githubusercontent.com/assets/6345473/12591809/a8003026-c437-11e5-9d65-b8d78ffc50c8.png)

**Comment by akberenz** [comment]
NearestNeighbor interpolation! And since bicubic (the current value) can also be desired, I've made it a config option, via 98ee07fe2a6de2e31bf1e40685c6fdf10989c497.

**Comment by tresf** [comment]
Thanks.  I agree that default should be `bicubic` as it's generally more desirable at high resolutions. :+1: 

**Edit:** Added documentation via https://github.com/qzind/qz-print/wiki/2.0-Pixel-Printing#image-interpolation.
