### ISSUE TITLE
USB "Poll" option

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#154]
@bberenz is there a way we can fetch only the latest message frame so that the scale reads are always the **current** scale status?

I like the streaming functionality you've entered, and I don't disagree with the behavior of read-data, since it gives us exactly as the OS would, but the buffered values are causing some issues with clients.  Can we dump the buffer and only get the latest message?  Perhaps qz.usb.pollData().

**Comment by akberenz** [comment]
Not easily. Currently the best way to do this would probably be to open a stream, and then just call read data as needed. 
It could be possible for us to read up the buffer and return the last non-empty message in a single call. But I am not sure how well this would work (if at all) on a continuous stream like a scale.

**Comment by tresf** [comment]
Closing as `wont-fix` for now. We can reopen at a later time if we determine this is possible.
