### ISSUE TITLE
Minimum Java Version

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#16]
@robertcasto @bberenz 

I see we have the `javac.target=1.6` (true for the applet version), but the WebSocket version requires 1.7.

I'm improving the WebSocket installers to do Java version checking, so I'd like to have the correct minimum version as part of the ant build for the WebSocket end of things, which I'll use as part of my installer checks as well via [`linux-installer.sh.in#L39`](https://github.com/qzind/qz-print/blob/1.9/qz-print/ant/linux/linux-installer.sh.in#L39)

**Comment by robertcasto** [comment]
The Jetty Webserver and Web Sockets need JDK7 so there really isn't a nice
way to go backward. Are users really not able to use JDK 1.7?

On Fri, Apr 10, 2015 at 12:41 AM, Tres Finocchiaro <notifications@github.com

> wrote:
> 
> @robertcasto https://github.com/robertcasto @bberenz
> https://github.com/bberenz
> 
> I see we have the javac.target=1.6 (true for the applet version), but the
> WebSocket version requires 1.7.
> 
> I'm improving the WebSocket installers to do Java version checking, so I'd
> like to have this as part of the ant build for the WebSocket end of things.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/16.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
@robertcasto I think you misunderstood the question.  I'm fine with 1.7 for sockets.  I'm inquiring about setting it as a hard requirement in ANT.  You've already done this for the applet side (albeit 1.6), I feel we just need to repeat for the socket build portion.

**Comment by tresf** [comment]
... and the point of this... once ant has the 1.7 requirement for the sockets, I'll make the desktop installers look for that minimum version as well (get the min-ver from ant, so the scripts aren't hard coded with 1.7, etc)

**Comment by robertcasto** [comment]
Ah, ok. The compile version is a build setting so it can be set easily. I'm
not looking at the code right now, but I believe that was pulled out to a
property file as well.

On Fri, Apr 10, 2015 at 8:57 PM, Tres Finocchiaro notifications@github.com
wrote:

> ... and the point of this... once ant has the 1.7 requirement for the
> sockets, I'll make the desktop installers look for that minimum version as
> well (get the min-ver from ant, so the scripts aren't hard coded with 1.7,
> etc)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/16#issuecomment-91733298.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
Right, this is a placeholder to get it in the same place (i.e. `project.properties`) so that I can pull from it too.

**Comment by tresf** [comment]
@robertcasto please let me know if your team will be able to tackle this one.

**Comment by robertcasto** [comment]
Yes, we will tackle this.

On Mon, Apr 13, 2015 at 2:15 PM, Tres Finocchiaro notifications@github.com
wrote:

> @robertcasto https://github.com/robertcasto please let me know if your
> team will be able to tackle this one.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/16#issuecomment-92449403.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
Pretty sure @bberenz tackled this one already.  Closing.
