### ISSUE TITLE
Density not specified vs. density null

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#161]
There is a discrepancy between setting the `density` to _null_ and not specifiying the `density`
1. When setting `density` to _null_ the image looks like this:
   
   ![image](https://cloud.githubusercontent.com/assets/12505463/12838367/50ef5616-cb9b-11e5-8dab-8970790c07db.png)
2. When the `density` is not declared, the image looks like this:
   
   ![image](https://cloud.githubusercontent.com/assets/12505463/12838405/bda46864-cb9b-11e5-966e-8b0f6ac0f12e.png)

**Comment by akberenz** [comment]
Fixed via b6b2a06f5b9b8825dd3762d81c1038c421065244

**Comment by klabarge** [comment]
These should behave identically, right?  It seems that when `density` is not specified, it defaults to 72dpi, and when `density` is set to _null_ it is set 600dpi

##### Density not specified

![image](https://cloud.githubusercontent.com/assets/12505463/13030631/89b4f13c-d27f-11e5-9971-747199425b7c.png)

##### Density set to null

![image](https://cloud.githubusercontent.com/assets/12505463/13030641/b3250e1c-d27f-11e5-97a7-a31f79556377.png)

**Comment by klabarge** [comment]
Please disregard this, I was testing with an outdated `qz-tray.js` file.  This worked with the updated file.
