### ISSUE TITLE
Alpha 2.0 not working on Edge browser

### ISSUE THREAD

**Issue by robert-gazsi** [qzind/qz-print#165]
Hi, this is the error I get in console:

```
SCRIPT12029: WebSocket Error: Network Error 12029, A connection with the server could not be established
```

Edge version is 25, I turned off antivirus.
It works ok on IE11 and Chrome.

Thanks.

**Comment by robert-gazsi** [comment]
I have the "Allow localhost loopback" setting on in about:flags.
I was testing with v2.0 alpha-1 release. 
I could not install newer ones, please see #166

**Comment by tresf** [comment]
A quick google search turns up this.... https://github.com/crossbario/autobahn-js/issues/134#issuecomment-87073222.

Which was implemented on 1.9 via https://github.com/qzind/qz-print/commit/d254333f6ace6fb5f792e0608adbe09e040766db, but never ported to 2.0 apparently. 

Thanks, we'll take a look.

**Comment by tresf** [comment]
@robert-gazsi Implemented `0.0.0.0` via e4bd2b7, but it's still broken.

After some testing, this appears to be suffering the same bug as #67.  Edge is blocking connections back to localhost because of the Internet Explorer security settings.

I'm not sure when this started (Edge 25 perhaps?) but selecting "Allow localhost loopback" doesn't seem to be enough to get this working.  In addition to this setting, you also have to modify the Internet Options on the PC as illustrated in #67.

**Comment by tresf** [comment]
Some more findings via https://confidentialfiles.wordpress.com/2013/09/05/internet-explorer-11-cannot-connect-to-local-host/.

There's a codeplex project which has a way of whitelisting the loopback connection here: http://loopback.codeplex.com/

![image](https://cloud.githubusercontent.com/assets/6345473/12891424/e44faac0-ce55-11e5-9781-9ccc5580af57.png)

For some reason the `/121` App Name works whereas the `/001` App Name does not.  Still investigating...

**Comment by tresf** [comment]
Ok... we're getting closer... :smile: 

http://stackoverflow.com/a/29177786/3196753

**Comment by tresf** [comment]
Got it... 

``` bat
CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.MicrosoftEdge_8wekyb3d8bbwe"
```

We'll add this to our `1.9` and `2.0` installers asap.

**Edit:**
- 1.9 available here: https://github.com/qzind/qz-print/releases/tag/v1.9.6
- 2.0 (will be) available here: https://github.com/tresf/qz-print/releases/tag/v2.0.0-RC1

**Comment by slprogrp** [comment]
@tresf ,  Isn't it a security issue to make Edge exempt from this?  By running the command:
`CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.MicrosoftEdge_8wekyb3d8bbwe"`

You are saying, not only your application, but any local application can send network traffic to Edge?

I can understand if you had a way to whitelist just your application, but you are essentially turning this security check off for MS Edge meaning all local applications can now send network traffic to it.

And if you roll it out in the installer of your product, the user will not even know they have lost this security feature...

How can you justify this?

**Comment by tresf** [comment]
@slprogrp I've moved discussion to the new repo at https://github.com/qzind/tray/issues/338.
