### ISSUE TITLE
Alpha 2.0 Windows 10 installers issue

### ISSUE THREAD

**Issue by robert-gazsi** [qzind/qz-print#166]
Hi,

For some reason, only the first release installer works:
[https://github.com/tresf/qz-print/releases/download/2.0.0-alpha1/qz-tray-2.0.0-alpha1-1.exe](https://github.com/tresf/qz-print/releases/download/2.0.0-alpha1/qz-tray-2.0.0-alpha1-1.exe)

All other newer ones (up to 6 at this moment) are downloading ok but are not starting.
I have Windows 10, and tried with AV off as well.

Thanks.

**Comment by tresf** [comment]
A quick google search turns up this.... https://github.com/crossbario/autobahn-js/issues/134#issuecomment-87073222.

Which was implemented on 1.9 via https://github.com/qzind/qz-print/commit/d254333f6ace6fb5f792e0608adbe09e040766db, but never ported to 2.0 apparently. 

Thanks, we'll take a look.

**Comment by tresf** [comment]
Sorry, I had replied to the wrong bug report.

We can't reproduce this.... Can you please post the output of your installer log for alpha6?

**Comment by tresf** [comment]
@robert-gazsi can you try the latest RC1 installer here?  https://github.com/qzind/qz-print/releases/tag/2.0.0-RC1

Note, nothing significant has changed in this version, but unless we can reproduce a problem with the installer, we'll have to close this as invalid.

**Comment by robert-gazsi** [comment]
Where can I get that log file?

**Comment by tresf** [comment]
Assuming you're installing on Windows, it will be in the installer window when "Show details" is pressed.

![image](https://cloud.githubusercontent.com/assets/6345473/12919251/40f95210-cf11-11e5-9c3c-130144bb075e.png)

**Comment by tresf** [comment]
Note, if you've recently upgraded Java, a botched Java install can render the installer useless, which is usually fixed by 1. Rebooting and then 2. Reinstalling the 32-bit and 64-bit versions from the [offline installers](https://java.com/en/download/manual.jsp).

**Comment by robert-gazsi** [comment]
I don't get to this window, only the allow to run warning box :(

**Comment by tresf** [comment]
> I don't get to this window, only the allow to run warning box :(

Are you on a solid state hard drive?  I would recommend forcing a scandisk and a reboot.  The installer should at least greet you with the "Next" screen.  Your issue is symptomatic of something interrupting the executable, often caused by a corrupt in-memory system process (or a virus, a blocking antivirus, bad HD sectors, or not rebooting after a Windows Update, etc).  In all of the scenarios, I don't think our installer has an issue, but we'd be happy to continue troubleshooting to get things going again.

**Comment by robert-gazsi** [comment]
A reboot actually got it solved!
It was Symantec AV, even though I disabled it...

Thanks a lot!

**Comment by tresf** [comment]
:+1:
