### ISSUE TITLE
Setting orientation to reverse-landscape does not work on Mac

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#179]
This bug has been migrated to https://github.com/qzind/tray/issues/7.

---

Tested using Mac OS X El Capitan and is reproducible on all major browsers.

Setting the page to `orientation: 'reverse-landscape'` does not work.  The image is set to `landscape`, but it is not shown on the opposite side of the page.

This can be reproduced using the `sample.html` page and either using "Print HTML" or "Print Image"

**Comment by tresf** [comment]
This bug has been migrated to https://github.com/qzind/tray/issues/7.
