### ISSUE TITLE
1.1in x 3.3in Dymo Label Support

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#183]
This bug report has been re-titled and migrated to https://github.com/qzind/tray/issues/12.

---

Placeholder for testing, configuration and output for [`99010`](http://www.amazon.co.uk/Sieko-99010-Compatible-Address-Label/dp/B0057NLF90) (1.1in x 3.3in, 28mm x 89mm) Dymo label format.

Related: #177

Sample label: (landscape)
[3.3in x 1.1in.pdf](https://github.com/qzind/qz-print/files/157116/3.3in.x.1.1in.pdf)
![image](https://cloud.githubusercontent.com/assets/6345473/13500089/ea433cbc-e12e-11e5-99ad-0bb16fe5fcac.png)

Sample label: (portrait)
[1.1in x 3.3in.pdf](https://github.com/qzind/qz-print/files/157132/1.1in.x.3.3in.pdf)
![image](https://cloud.githubusercontent.com/assets/6345473/13500164/5ac2570c-e12f-11e5-9545-bd60757204b5.png)

**Comment by klabarge** [comment]
It appears that changing the `orientation` setting for PDF's currently does not work.

I had to use an image to test how the `orientation` setting currently functions.

##### Config

``` js
var size = { width: 3.3, height: 1.1};
var config = qz.configs.create('Microsoft XPS Document', { orientation: 'landscape', units: 'in', size: size });
```

##### Original PDF (3.3in x 1.1in)

   ![image](https://cloud.githubusercontent.com/assets/12505463/13513169/1c7dae5e-e16d-11e5-91c1-b3fe9dfee1b4.png)
1. Using the PDF above, I was not able to view any differences between forcing `landscape` or `portrait`
   
   ![image](https://cloud.githubusercontent.com/assets/12505463/13513437/e46e3842-e16e-11e5-8c5f-64e7bbac3267.png)
2.  However, when I tried doing the same thing with an image, we can see that the image is rotated 
   
   ![image](https://cloud.githubusercontent.com/assets/12505463/13513712/020cb782-e171-11e5-83d0-b8579acc0aab.png)
3. Then, when I changed the page dimensions, I got:
   
   ![image](https://cloud.githubusercontent.com/assets/12505463/13514078/a4ad8cc6-e173-11e5-8a10-72448d079995.png)
   
   **Note:** Even after adding a printer with the above dimensions to my operating system, and using the original image that was designed for that size, I was unable to get rid of the gap at the bottom of the image.

**Comment by tresf** [comment]
> I was unable to get rid of the gap at the bottom of the image.

Right, because the dimensions were off by a considerable margin when compared to the label mentioned.

Here's an illustration showing it fixed to a 3:1 ratio... 

**GREEN:**  stretch width to be proportional
**BLUE:**  shrink height to be proportional

![image](https://cloud.githubusercontent.com/assets/6345473/13518169/1c090f14-e199-11e5-95d7-e46f064a21b7.png)

> changing the orientation setting for PDF's currently does not work.

Confirmed, except mine does portrait orientation every time (using PDFCreator, not XPS).

Upstream convo: https://issues.apache.org/jira/browse/PDFBOX-2922

@bberenz I've spent some time reading up on this and I'm not sure how best to approach the force-orientation in code.

**Comment by akberenz** [comment]
It looks like PDFBox is internally forcing a swap of dimensions when width > height to avoid the exception thrown by the `MediaSize` class when this condition is met. 
We manage to skirt around this issue with image printing by using the `MediaPrintableArea` class, but as we have no control over the pdf printing logic I'm not sure there is anything we can do here. 
The XPS printer is a bit .. loose anyways. Have you seen any of the results when using an actual label printer with PDFs?

**Comment by tresf** [comment]
@bberenz using `PDFCreator`, this auto-rotates as documented.  We have some options... 
- Echo a warning and ignore this
- Try to tackle this via PDFBOX-recommended method

To [quote the relevant portions from the developer](https://issues.apache.org/jira/browse/PDFBOX-2922)... 

> If you want to customise the orientation, then you don't want to use `PDFPageable`. The purpose of a `Pageable` interface is to let the source document determine its own layout. If you want to do something custom, then skip the `Pageable` and use a `Printable` directly.

I do much prefer the standard behavior, but how much work is the `Printable` portions he speaks of?  Can we use `Printable` if orientation is provided and fallback onto `Pageable` if not?

**Comment by tresf** [comment]
This bug report has been re-titled and migrated to https://github.com/qzind/tray/issues/12.
