### ISSUE TITLE
Setting margins does not work in HTML and image printing

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#185]
This bug has been migrated to https://github.com/qzind/tray/issues/8

---

These printing results are identical between all browsers and platforms.

I got these images using the `sample.html` and leaving all of the default printing options except for adding 2 inches to the margins.
1. Two inch margins around HTML:
   ![image](https://cloud.githubusercontent.com/assets/12505463/13656196/d6518e94-e632-11e5-80c4-7518afe0096d.png)
2. Two inch margins around an image:
   ![image](https://cloud.githubusercontent.com/assets/12505463/13656175/99fc24c2-e632-11e5-91bf-af9a124c1e8f.png)
3. For comparison, this works fine when setting margins for a PDF:
   ![image](https://cloud.githubusercontent.com/assets/12505463/13656116/21725652-e632-11e5-9c35-d196cb1b9cf7.png)

**Comment by tresf** [comment]
This bug has been migrated to qzind/tray#8
