### ISSUE TITLE
qz tray 1.9.4

### ISSUE THREAD

**Issue by sumanthkavuri1** [qzind/qz-print#192]
while running qz tray from web based application. we are getting certificate is unknown issue. this computer is behind firewall with content filtering. do we need to allow any particular URL for qz tray to work properly.

**Comment by tresf** [comment]
> do we need to allow any particular URL for qz tray to work properly.

No you do not.

The certificate issues are all server-side driven and can be configured and resolved by following our signing messages tutorial.

https://qz.io/wiki/1.9-signing-messages

If you've already followed this tutorial, please reach out to the appropriate support channel.
