### ISSUE TITLE
QZ not working over WSS using IP machine

### ISSUE THREAD

**Issue by giolazzareschi** [qzind/qz-print#195]
Hi!

I'm facing a strange issue and any help will be apreciated. 

I've been using qz (the paid one) to work with my clients using one pc as "server" and other pc's on network just pont to its IP to make print happens. Ok this always worked fine with ws protocol but in last days I just implemented https on my website and the prints just stopped. Well, searching for an answer I've found this:

[Remove static localhost bindings in code #91](https://github.com/qzind/qz-print/issues/91)

But trying to work with the solutions the thing just don't happen.

I tried to create the certs for the wss but I receive an failure message when qz tryies to print. 

My scenario is: I use the host machine IP to connect with QZ but receive this message:

![image](https://cloud.githubusercontent.com/assets/4623190/24277699/a647afb0-101d-11e7-99b9-fdcc24e27800.png)

This ip is the host machine. Neither this or guests machines works.

I dont know if i was clear enough but any help will be helpful. Regards :)

**Comment by tresf** [comment]
Can you please reopen this on [`qzind/tray`](https://github.com/qzind/tray) tracker? This codebase is no longer supported.
