### ISSUE TITLE
Qz Notification Allow

### ISSUE THREAD

**Issue by mdestafadilah** [qzind/qz-print#198]
I checked, for allow. but, acctually it's blocked, not remember i checked. 
![qz](https://user-images.githubusercontent.com/5575882/29649347-a3edb93a-88bd-11e7-8191-973cf2538212.png)

**Comment by tresf** [comment]
This is intentional, messages need to be digitally signed to suppress warning dialogs.

https://qz.io/wiki/2.0-signing-messages
