### ISSUE TITLE
Error JSONObject["data"] is not a JSONArray (Microsoft Edge only)

### ISSUE THREAD

**Issue by s-berney** [qzind/qz-print#199]
**Edit:** Moved here https://github.com/qzind/tray/issues/235.

Hello,

We have an issue on Microsoft Edge (v40) when launching the print, we got this error :
![image](https://user-images.githubusercontent.com/10452430/30443455-d96d9648-997f-11e7-8de2-ba5b08f6558b.png)

Code is :
```
        var config = qz.configs.create(printer_name, {
          margins: { top: 0, right: 0, bottom: 0, left: 0 },
          size: {width: 210, height: 297}, units: 'mm', 
          interpolation: "nearest-neighbor",
          scaleContent: "false",
          orientation: 'portrait',
          copies: 1
        });
        var data = [{ 
          type: 'pdf', 
          data: getPath() + "/temp/file16201.pdf"
        }];
        qz.print(config, data).catch(function(e) {
          console.error(e);
          alert('Error printing:\n\n\t' + e);
        });
```

On Firefox, all is working...

**Comment by tresf** [comment]
@s-berney can you reopen this issue on our new bug tracker? https://github.com/qzind/tray/issues/new

**Comment by tresf** [comment]
Superseded by qzind/tray#235.
