### ISSUE TITLE
Timeout on read

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#2]
@robertcasto is this normal, or related to serial support?  I would assume we wouldn't ever want the socket to shut itself down.

```
SEVERE: Server error: Timeout on Read
Nov 25, 2014 11:44:27 PM qz.ws.PrintSocket onClose
INFO: WebSocket close: 1001 - Idle Timeout
```

**Comment by robertcasto** [comment]
After a while the socket will close. That is normal because it is a
resource that the browser doesn't want to keep open all the time. Another
attempt at printing something should reestablish the connection if it is
closed. I'll run some tests and make sure that is working correctly.

On Tue, Nov 25, 2014 at 11:54 PM, Tres Finocchiaro <notifications@github.com

> wrote:
> 
> @robertcasto https://github.com/robertcasto is this normal, or related
> to serial support? I would assume we wouldn't ever want the socket to shut
> itself down.
> 
> SEVERE: Server error: Timeout on Read
> Nov 25, 2014 11:44:27 PM qz.ws.PrintSocket onClose
> INFO: WebSocket close: 1001 - Idle Timeout
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/2.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by robertcasto** [comment]
Keep alive will be implemented to ensure the browser can receive messages
from the server at any time.

On Wed, Nov 26, 2014 at 12:22 AM, Robert Casto casto.robert@gmail.com
wrote:

> After a while the socket will close. That is normal because it is a
> resource that the browser doesn't want to keep open all the time. Another
> attempt at printing something should reestablish the connection if it is
> closed. I'll run some tests and make sure that is working correctly.
> 
> On Tue, Nov 25, 2014 at 11:54 PM, Tres Finocchiaro <
> notifications@github.com> wrote:
> 
> > @robertcasto https://github.com/robertcasto is this normal, or related
> > to serial support? I would assume we wouldn't ever want the socket to shut
> > itself down.
> > 
> > SEVERE: Server error: Timeout on Read
> > Nov 25, 2014 11:44:27 PM qz.ws.PrintSocket onClose
> > INFO: WebSocket close: 1001 - Idle Timeout
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/qzind/qz-print/issues/2.
> 
> ## 
> 
> Robert Casto
> _Owner | SellersToolbox_
> p: 1-513-847-4942
> c: 1-513-886-1550
> e: casto.robert@gmail.com
> www.sellerstoolbox.com
> Tools for Amazon Sellers

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
I assume this is safe to close.  I will reopen if this issue resurfaces.
