### ISSUE TITLE
Signing Preemptive Functions

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#24]
@robertcasto @bberenz 

One of our customers is inquiring why we sign the preemptive function calls (ones that work without signing), i.e.

``` javascript
preemptive: {isActive: '', getVersion: '', getPrinter: '', getIP: '', getMac: '', getLogPostScriptFeatures: ''},
```

His argument is that initial load requires 6 signings to occur weighing in a 500ms load time on page refresh.

I tend to agree... If the untrusted version doesn't require a signature on these functions, why would the trusted version require a signature?

**Comment by tresf** [comment]
Ok, this is what I've come up with... feedback appreciated:

**`qz-websocket.js`**

``` javascript
 function isPreemptive(message) {
    return (Object.keys(qzConfig.preemptive).indexOf(JSON.parse(message).method)) != -1;
 }
```

**`sample.html`**

``` javascript
 function signRequest(toSign, callback) {
    if (isPreemptive(toSign)) {
        return callback();
    }

       /*
       $.ajax({
       ...
 }
```

**Comment by tresf** [comment]
This solution may be a bit cleaner... 

``` javascript
websocket.sendObj = function(objMsg) {
        var msg = JSON.stringify(objMsg);

        console.log("Sending " + msg);
        var ws = this;

        if (objMsg.method === 'listMessages') {
            ws.send(msg);
        } else {
/*
 * STARTS HERE
 */
            // Don't sign preemptive messages
            if ((Object.keys(qzConfig.preemptive).indexOf(objMsg.method)) != -1) {
                ws.send(msg);
            } else {
/*
 *
 */
                signRequest(msg,
                            function(signature) {
                                ws.send(signature + msg);
                            }
                );
            }
        }
    };
```

**Comment by akberenz** [comment]
I was about to suggest that second method. Though you can combine the if statements, since they both send an unsigned message to the socket if true.

**Comment by tresf** [comment]
good call.

**Comment by tresf** [comment]
Ok, that fixes those, what about `findPrinter(...);`, etc?

**Comment by tresf** [comment]
>  what about findPrinter(...);, etc?

@robertcasto @bberenz any help on this one?

**Comment by akberenz** [comment]
Well, what needs done with those methods?
If you want them excluded from signing, then it would probably be best to create an array of method names that go straight through. And if the number of methods _to_ sign is less, then it might be better to make the array of those methods instead.
But given that `findPrinter` actually sets the printer being used, it might be better to leave it as needing signed.

**Comment by tresf** [comment]
> Well, what needs done with those methods?

I'll repeat this line from the original post as I think it sums it up better... 

> > If the untrusted version doesn't require a signature on these functions, why would the trusted version require a signature?

... 

> But given that findPrinter actually sets the printer being used, it might be better to leave it as needing signed.

If that is the case, shouldn't we show a warning for it with the unsigned version?  This is about consistency and efficiency.  I'm not partial to one approach versus the other.

**Comment by tresf** [comment]
@robertcasto I know it's a holiday weekend, but if we can make a decision on this, it is the one thing I'm waiting on before releasing the next beta version.

**Comment by robertcasto** [comment]
Hi Tres,

Sorry. I was under a car replacing an axle most of the day. I will look
into this first thing in the morning.

Robert

**Comment by tresf** [comment]
The Finocchiaro's have a lot of elbow grease in that area. :)  Thanks for chiming in.

**Comment by tresf** [comment]
@robertcasto I can take a look at this tonight if needed, I just think your staff would be more familiar with this portion of the codebase.  Either way, it is something that I'd like to have sorted prior to our public beta.

I need to do some finalized testing to our portal for our existing subscribers and then we'll be sending out download links, which I hope to do in the coming days. :)

**Comment by robertcasto** [comment]
Can we review this over the phone? We have a couple questions.

**Comment by akberenz** [comment]
Gateway dialog should appear now for all resource access functions (8ae51b0a2107b8606140a88d222db86926c1b7b7). Alter the `privilegedMethods` list in the `PrintSocket` class if any methods have been missed or shouldn't be included.

**Comment by tresf** [comment]
Thanks, this is working well.  I'll reopen if we have any issues.
