### ISSUE TITLE
Open File Location not working on Apple

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#35]
The About dialog button to open the QZ Tray working directory "Open File Location" doesn't work.

Ideally, this would open the Finder application to the `/Applications/QZ Tray/` directory.  This button is offered as a convenience to quickly get to the `demo` folder.

Steps to reproduce:
1. Install QZ Tray on a Mac (OS 10.7 or higher)
2. Once the icon goes from Red/Yellow to Green, right click, advanced, open file location

Temporary work-around:
1. Open Finder
2. Click Applications
3. Locate the QZ Tray application
4. Right click, Show Package Contents

**Comment by Vzor-** [comment]
This was fixed as of 4c1a2685618940b98d055febf622db30b6e81da1

**Comment by tresf** [comment]
:+1:
