### ISSUE TITLE
Remove or refactor plugin directories

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#36]
@robertcasto @bberenz do we still need the source code for pdf-renderer or jssc as part of our project source code?

Can we easily refactor the code to just be a single `qz-print` directory?

**Comment by akberenz** [comment]
We should just be using the compiled jars now, so those directories can be removed.

**Comment by tresf** [comment]
Ok, great.  I'm not sure how much of the idea project will break when we bump qz-print up to its parent tho.  Also, the nested readme.txt will have to go away. Is this something you can do quickly?

-Tres

**Comment by akberenz** [comment]
Yes, 41cf5ec24cd8843a2d6279dbf3c7895cf2ef6f94
Everything should be working fine, but let me know if something broke.

**Comment by tresf** [comment]
Thanks!  I'll do some tests and see how things are working.

-Tres

**Comment by tresf** [comment]
Seems to be good.  Had a few lines to cleanup per 448ee03 and now we're good.  Thanks!!

**Comment by tresf** [comment]
One more patch https://github.com/qzind/qz.io/commit/29df8a38e8f2151ebe4d32099d268f11bc1ffd2d.

-Tres

**Comment by tresf** [comment]
And one more.... :wink:  qzind/qz.io@fc0bc60
