### ISSUE TITLE
The installation of 'QZ Tray' failed on OS X

### ISSUE THREAD

**Issue by rostislav-rocket** [qzind/qz-print#40]
Hi, I couldn't install 'QZ Tray'.

The version of client: 1.1.9-1
The version of OS X: 10.10.3

Please see screens.
![screen shot 2015-06-11 at 11 26 05](https://cloud.githubusercontent.com/assets/9251275/8104031/c930ddb8-102d-11e5-9fdc-0a4b56e847d1.png)
![screen shot 2015-06-11 at 11 29 32](https://cloud.githubusercontent.com/assets/9251275/8104032/cb2d1de8-102d-11e5-869b-8fec913aac79.png)

**Comment by alfonsodev** [comment]
:+1:  Same error here

**Comment by rostislav-rocket** [comment]
I apologise, the problem was I had no Java installed https://java.com/en/download/
However, you could add more informative error message to the installer

PS. 'Getting Started' in https://github.com/qzind/qz-print/blob/1.9/README.md currently leads to 404 - https://github.com/qzind/qz-print/blob/1.9/Getting-Started

**Comment by tresf** [comment]
Thanks for the bug report.  This is related to #37 (fixed) which was prompting to install the **wrong** Java version.

I'm still trying to figure out how to display a message via the apple [`preinstall`](https://github.com/qzind/qz-print/blob/1.9/ant/apple/apple-preinstall.sh.in) script.  If you or anyone else can find a place to add it, we'd be much obliged.
