### ISSUE TITLE
Fedora Support

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#51]
**QZ Tray Fedora Tasks**
-  [x]  Add proper Firefox detection / cert installation
-  [ ]  ~~Draw tray icon in correct area of OS (possible upstream bug per [redhat#1014448](https://bugzilla.redhat.com/show_bug.cgi?id=1014448), [gnome#648773](https://bugzilla.gnome.org/show_bug.cgi?id=648773))~~ upstream bug, won't fix.
-  [x]  Allow interaction with System Tray icon on Gnome3 / Gnome Shell
-  [x] Software fails to auto-launch due to permission issues with `/opt/qz-tray`

The first issue is caused by the Firefox detection script assuming `/usr/bin/firefox` is a symlink (this is how Ubuntu does it).  Instead on Fedora, Firefox is launched by a shell script which does on-the-fly platform detection.  We are still investigating the best method for determine he Firefox installation path.

The second and third issues are more of a mystery.  Depicted below is the behavior we're seeing after adding some compat code for the menu placement per df8e40e.  The menu appears under the mouse cursor now, however the menu is not selectable and the icon placement is still incorrect.

![image](https://cloud.githubusercontent.com/assets/6345473/8386774/e8a07b6e-1c20-11e5-9436-1dc5c6ba6b90.png)

**Comment by Vzor-** [comment]
Please add 
1. [ ] Software fails to auto-load due to permission issues with `/opt/qz-tray`

**Comment by tresf** [comment]
@Vzor-, added.

**Comment by tresf** [comment]
The tray icon issue appears to be from upstream.  Documented here [redhat#1014448](https://bugzilla.redhat.com/show_bug.cgi?id=1014448), [gnome#648773](https://bugzilla.gnome.org/show_bug.cgi?id=648773) quoted below: 

> **Description of problem:**
> - Java apps with system tray icons do not work properly with GNOME Shell. See below.
> 
> Version-Release number of selected component (if applicable):
> - `java-1.7.0-openjdk-1.7.0.60-2.4.2.5.fc19.x86_64`
> 
> **How reproducible:**
> - Every time
> 
> **Steps to Reproduce:**
> 1. Get and run the http://docs.oracle.com/javase/tutorial/uiswing/misc/systemtray.html demo application
>    2.
>    3.
> 
> **Actual results:**
> System tray icon shows up in notification area (though only if you open the Activities view and pull down at the bottom of the screen). However the icon seems to be incorrectly scaled (the image is at the top left of the icon instead of being scaled to fill it). Worse, the tooltip and pop-up menu do not work at all. And a useless icon shows up in the running apps list labelled misc-TrayIconDemo.
> 
> **Expected results:**
> - Tray icon works as expected. No useless icon in apps list.
> 
> **Additional info:**
> - `java-1.8.0-openjdk` seems broken as well.

---

> Looks like that all programs with tray icons work in gnome shell (their tray icon appears in the bottom area), except Java applications. Their tray icon appear as a very small window among windows. There is something wrong with the java tray icons in Gnome shell.
