### ISSUE TITLE
NSIS shortcut creation fails when run by non-admin user

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#55]
**Update:** This issue has been resolved in 1.9.3.  Download it here:  https://qz.io/download

The installer appears to succeed, but the page won't load after install.

**Edit:** This seems to be a problem when the installer is launched by a non-admin user.  This should be fairly easy to reproduce.

> `Windows cannot access the specified device, path, or file.  You may not have the appropriate permissions to access the item.`

The software is installed properly, but the shortcut for launching it isn't accessible and it won't auto-launch.

~~Possible issue with Japanese-localized version of Windows 7.  Will obtain a copy and try to reproduce.~~  Installed Japanese version of Windows 7 and it doesn't appear to be related.
~~Possible resource:  http://www.scratchpaper.com/home/faq~~
~~We may also need to add the `Unicode true` line to the `.nsi` script.~~

![image](https://cloud.githubusercontent.com/assets/6345473/8458848/5a58bf72-1fe7-11e5-85a4-c8c888573162.png)

**Comment by tresf** [comment]
This issue seems to be caused by a non-administrator user starting the installer.  Steps to reproduce:

Steps to reproduce:
1. Create non-administrator user
2. Sign in as non-administrator user
3. Download QZ Tray
4. Run QZ Tray installer
5. When prompted, enter administrator password
6. Install fails

**Comment by klabarge** [comment]
The same issue happens on EN Windows 7.

![image](https://cloud.githubusercontent.com/assets/12505463/8459448/4c6bd9f4-1feb-11e5-967b-fcf373a4fd36.png)

**Comment by tresf** [comment]
@klabarge can you test this patched installer and see if it fixes the issue:

https://github.com/qzind/qz-print/releases/download/v1.9.3/qz-tray-1.9.3.exe

**Comment by tresf** [comment]
Closed via: https://github.com/qzind/qz-print/commit/1000203caa2ee3e1ee77f92620c46fb6e2b9664c
