### ISSUE TITLE
Print Warnings Display Improperly

### ISSUE THREAD

**Issue by klabarge** [qzind/qz-print#58]
On all browsers, the warning messages display improperly on page load up.  This is a random event and does not happen regularly.

![image](https://cloud.githubusercontent.com/assets/12505463/8610362/0cc95714-267f-11e5-8860-273b5592545f.png)

**Comment by tresf** [comment]
I believe this to be related to this article:  http://www.widecodes.com/vyzNmzqXeg/joptionpane-displays-a-blank-window.html

Basically, I believe the JOptionPane is trying to draw the dialog on the wrong thread (the main thread which starts the WebSocket listener).

To fix this, we should be able to use SwingUtilities to move the code to the Event Dispatch Thread (EDT) .  @Vzor- has partially discovered this issue in the pursuit to fix the Fedora tray icon per https://github.com/Vzor-/qz-print/commit/5f5b2014d3e143b3295633a9b8236763878673c8#diff-bf5db5ca98768d9474ab173b599dbeb3R217.

This should be covered in his branch and fixed 1.9.4.

**Comment by tresf** [comment]
Closed via #62.  This fix will be available starting with the 1.9.4 release.
