### ISSUE TITLE
Could not find the main class / Exception in thread "main"

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#66]
**Issue:**

```
Could not find the main class: qz.ws.PrintWebSocketServer. Program will exit.

Exception in thread "main" java.lang.UnsupportedClassVersionError: 
org/eclipse/jetty/server/Handler : Unsupported major.minor version 51.0
```

**Cause:**

Java 7 or higher is missing from the system. Java 7 or higher is required to run QZ Tray

**Resolution:**

Install Java 7 or higher from the Oracle website.

**Comment by fmq** [comment]
Hello

I have this same issue but Java 1.8 is installed on my system. 

Any ideas?

![errorqz](https://cloud.githubusercontent.com/assets/881660/23268698/47c1973c-f9cd-11e6-83ec-6e4092cc9840.JPG)

**Comment by tresf** [comment]
99% of the issues are resolved following this guide.

https://qz.io/wiki/faq#cannot-launch-software

In short:
1. Remove `JAVA_HOME` references from ENV.  Make sure no lingering versions of java.exe in `PATH`
2. Reboot computer
3. Reinstall Java from offline installer

**Comment by fmq** [comment]
eliminating an old reference to an un existing java worked!

Thanks you for your quick response!

**Comment by Seshabhattar** [comment]
Issue Resolved after Uninstalling  64 bit version of java 1.8 and reinstalled java 1.8 _131 32 bit (X86).
Disable all other java versions and use only 32 bit version.
