### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by bkrajendra** [qzind/qz-print#71]
What could be the reason behind this error while trying to do any operation in sample.html.
It connects properly, but get this error in console if I press any command button in sample.html and nothing happens.

```
TypeError: Cannot read property 'apply' of undefined
    at WebSocket.websocket.onmessage (http://localhost/pos/qz-clean/new/qz-print/js/qz-websocket.js:192:49)
```

Also qz-print log shows:

```
[WARNING] 2015-08-07 11:36:21 - Signature length not correct: got 6 but was expecting 256
[INFO] 2015-08-07 11:36:21 - Blocked An anonymous request from accessing local resources

```

This started happening after i done some trial n error with certificate installation.. or ne I have blocked the request.. don't know..
But is there any solution to this ?

**Comment by bkrajendra** [comment]
Got resolved!
Accidently checked "Block Anonymous request"
Unchecking it in qz-tray resolved it.

**Comment by tresf** [comment]
Thanks for the feedback!
