### ISSUE TITLE
PDFs fail on Applet

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#9]
@robertcasto @bberenz 

It appears something is broken with the new applet (non-websockets) as when I build and try to print a PDF or anything in the PostScript column, it throws an exception.

**Comment by tresf** [comment]
@robertcasto @bberenz I'm having a hard time reproducing this... I'll leave it open in case it resurfaces, but things seem to be working just fine at the moment.

**Comment by robertcasto** [comment]
Glad to hear that you are having trouble. :)

If this cannot be reproduced in the next few days, then should we close this? Any idea why you might have seen it in the first place?

On Thu, Mar 19, 2015 at 10:42 AM, Tres Finocchiaro <notifications@github.com

> wrote:
> 
> I'm having a hard time reproducing this... I'll leave it open in case it
> resurfaces, but things seem to be working just fine at the moment.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/qzind/qz-print/issues/9#issuecomment-83612585.

## 

Robert Casto
_Owner | SellersToolbox_
p: 1-513-847-4942
c: 1-513-886-1550
e: casto.robert@gmail.com
www.sellerstoolbox.com
Tools for Amazon Sellers

**Comment by tresf** [comment]
@robertcasto I was trying to reproduce with the websockets version which works.  This bug is with the applet version... 

I figured out why it is happening... I believe your'e setting a boolean flag for `printPS`, but never using it.

https://github.com/qzind/qz-print/blob/1.9/qz-print/src/qz/PrintApplet.java#L609

Can you or @bberenz take a look?

Also if I can get some info on the CRL stuff from Steven or Brett that would be great. :+1:

**Comment by tresf** [comment]
Closed via b03b53f63535330c7c50adcfe9d908398f6a5402. (Thanks Brett)
