### ISSUE TITLE
Option to Suppress Tray Messages

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#92]
On Windows, you can suppress tray messages, but only if the icon is hidden.

We like these messages for the demo page (and for all dev/testing) but they are way too verbose for production use.  We need a way of disabling them for a particular connection.

   ![image](https://cloud.githubusercontent.com/assets/6345473/9968904/5e87226c-5e19-11e5-8065-d0dcb62ebbe3.png)

Mac does not appear to have such an option. 

The software should have an option to suppress the popup messages.

**Comment by Vzor-** [comment]
I'm starting this one on my fork.

**Comment by tresf** [comment]
Closed via 8e10923

This feature will be available in 1.9.5, expected on or around December 23, 2015.
