### ISSUE TITLE
Singleton QZ Tray Instance

### ISSUE THREAD

**Issue by tresf** [qzind/qz-print#95]
Request to allow QZ Tray to be aware of other running instances and shut itself down.

**Comment by ocaloke** [comment]
I think this would be a nice feature to add, as I have seen users with multiple instances running.

**Comment by Vzor-** [comment]
I am currently working on this.

**Comment by tresf** [comment]
FYI, work is in progress here:  https://github.com/qzind/qz-print/compare/1.9...Vzor-:1.9

**Comment by tresf** [comment]
Implemented via #122.  This feature will be available in 1.9.5, which should be ready before the holidays after we run it through some rigorous testing.
