### ISSUE TITLE
QZ TRAY Corrupt or missing file supplied

### ISSUE THREAD

**Issue by atom32k** [qzind/qz-print#97]
Hi,

I've been using and still use successfully qzprint in production as Java applet without any problems and now I'm adding QZ Tray support but with issues.

I'm sending png images to printer and that works OK with Java applet but with QZ tray I only get "Corrupt or missing file supplied".

Usage as following:

``` js
qz.appendImage("http://localhost:8084/myapp/getLabelImage?image_name=5417_label-1.png")

window['qzDoneAppending'] = function() {
        qz.printPS();
        window['qzDoneAppending'] = null;
};
```

Checking web app logs it doesn’t even hit that URL to get image (with absolute path to image at local file system it works). 

Thanks in advance,
Thomas

**Comment by tresf** [comment]
This is likely due to the file being inaccessible by QZ Tray.  Please try to move the PNG to a web location that is not behind authentication and see if that helps.

I'm closing this as it is a support request, but feel free to continue commenting here.

**Comment by atom32k** [comment]
Well that could be the case if QZ Tray would try to make request to web server (http://localhost:8084/myapp/getLabelImage?image_name=5417_label-1.png) and try to get that image to send to printer but nothing is hitting web server with that request (form QZ Tray) in first place.

**Comment by tresf** [comment]
@atomekk there are a lot of variables in play here, but I can reassure you that our `sample.html` appends images by URL and this functionality was tested thoroughly for the 1.9.4 release without any issues.  So, I can promise that this functionality works despite what you are observing in your HTTP logs.

> nothing is hitting web server with that request (form QZ Tray) in first place.

Perhaps a race condition is happening, but we'd need more details to troubleshoot that.  Can you please try to use a hard-coded URL that is not behind an authenticated location?

**Comment by atom32k** [comment]
URL is behind authenticated location but I would see in web app server logs that something is trying to make request and I'm sure QZ Tray don't even try to do any.
For time being I just feed qz.appendImage() with base64 URI and that works.
